-- 79310 특약 가입나이 데이터 즉시 수정 스크립트

-- 1. 현재 데이터 확인
PROMPT ===== 79310 특약 현재 데이터 확인 =====
SELECT CODE, PRODUCT_NAME, PAY_TERM, ENTRY_AGE_M, ENTRY_AGE_F, PERIOD_LABEL
FROM UW_CODE_MAPPING 
WHERE CODE = '79310'
ORDER BY CODE, PERIOD_LABEL, PAY_TERM;

-- 2. 허혈심장질환진단특약 관련 모든 데이터 확인
PROMPT ===== 허혈심장질환진단특약 관련 데이터 =====
SELECT CODE, PRODUCT_NAME, PAY_TERM, ENTRY_AGE_M, ENTRY_AGE_F, PERIOD_LABEL
FROM UW_CODE_MAPPING 
WHERE PRODUCT_NAME LIKE '%허혈심장%'
ORDER BY CODE, PERIOD_LABEL, PAY_TERM;

-- 3. 해약환급금미지급형V2 관련 데이터 확인
PROMPT ===== 해약환급금미지급형V2 관련 데이터 =====
SELECT CODE, PRODUCT_NAME, PAY_TERM, ENTRY_AGE_M, ENTRY_AGE_F, PERIOD_LABEL
FROM UW_CODE_MAPPING 
WHERE PRODUCT_NAME LIKE '%해약환급금%' 
   OR PRODUCT_NAME LIKE '%미지급형%'
ORDER BY CODE, PERIOD_LABEL, PAY_TERM;

-- 4. 79310 특약 가입나이 데이터 수정 (해약환급금미지급형V2)
PROMPT ===== 79310 가입나이 데이터 수정 시작 =====
UPDATE UW_CODE_MAPPING 
SET ENTRY_AGE_M = '0~30세',
    ENTRY_AGE_F = '0~30세',
    UPDATED_AT = CURRENT_TIMESTAMP
WHERE CODE = '79310' 
  AND PRODUCT_NAME LIKE '%허혈심장%'
  AND (PERIOD_LABEL LIKE '%해약환급금%' 
       OR PERIOD_LABEL LIKE '%미지급형%'
       OR PERIOD_LABEL LIKE '%V2%');

-- 5. 수정 결과 확인
PROMPT ===== 수정 결과 확인 =====
SELECT CODE, PRODUCT_NAME, PAY_TERM, ENTRY_AGE_M, ENTRY_AGE_F, PERIOD_LABEL
FROM UW_CODE_MAPPING 
WHERE CODE = '79310'
ORDER BY CODE, PERIOD_LABEL, PAY_TERM;

-- 6. LEARNED_PATTERN에서 79310 관련 잘못된 패턴 삭제
PROMPT ===== LEARNED_PATTERN 79310 관련 데이터 삭제 =====
DELETE FROM LEARNED_PATTERN 
WHERE INSU_CD = '79310' 
  AND FIELD_NAME = 'ageRange';

-- 7. 올바른 패턴 재삽입
PROMPT ===== 올바른 패턴 재삽입 =====
INSERT INTO LEARNED_PATTERN (
    PATTERN_ID, INSU_CD, FIELD_NAME, PATTERN_VALUE, 
    CONFIDENCE_SCORE, LEARNING_SOURCE, PRIORITY, IS_ACTIVE,
    CREATED_AT, UPDATED_AT
) VALUES (
    learned_pattern_seq.NEXTVAL, '79310', 'ageRange', '0~30세',
    100, 'MANUAL_CORRECTION', 100, 'Y',
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);

-- 8. payTerm도 함께 수정 (해약환급금미지급형V2는 20년, 30년납)
INSERT INTO LEARNED_PATTERN (
    PATTERN_ID, INSU_CD, FIELD_NAME, PATTERN_VALUE, 
    CONFIDENCE_SCORE, LEARNING_SOURCE, PRIORITY, IS_ACTIVE,
    CREATED_AT, UPDATED_AT
) VALUES (
    learned_pattern_seq.NEXTVAL, '79310', 'payTerm', '20년납, 30년납',
    100, 'MANUAL_CORRECTION', 100, 'Y',
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);

-- 9. insuTerm도 함께 수정 (해약환급금미지급형V2는 80세, 90세, 100세만기)
INSERT INTO LEARNED_PATTERN (
    PATTERN_ID, INSU_CD, FIELD_NAME, PATTERN_VALUE, 
    CONFIDENCE_SCORE, LEARNING_SOURCE, PRIORITY, IS_ACTIVE,
    CREATED_AT, UPDATED_AT
) VALUES (
    learned_pattern_seq.NEXTVAL, '79310', 'insuTerm', '80세만기, 90세만기, 100세만기',
    100, 'MANUAL_CORRECTION', 100, 'Y',
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);

-- 10. renew도 함께 수정 (해약환급금미지급형V2는 비갱신형)
INSERT INTO LEARNED_PATTERN (
    PATTERN_ID, INSU_CD, FIELD_NAME, PATTERN_VALUE, 
    CONFIDENCE_SCORE, LEARNING_SOURCE, PRIORITY, IS_ACTIVE,
    CREATED_AT, UPDATED_AT
) VALUES (
    learned_pattern_seq.NEXTVAL, '79310', 'renew', '비갱신형',
    100, 'MANUAL_CORRECTION', 100, 'Y',
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);

-- 11. 최종 결과 확인
PROMPT ===== 최종 결과 확인 =====
SELECT INSU_CD, FIELD_NAME, PATTERN_VALUE, LEARNING_SOURCE
FROM LEARNED_PATTERN 
WHERE INSU_CD = '79310'
ORDER BY FIELD_NAME;

-- 12. 통계 업데이트
PROMPT ===== 통계 업데이트 =====
UPDATE LEARNING_STATISTICS 
SET TOTAL_PATTERNS = (
    SELECT COUNT(*) FROM LEARNED_PATTERN WHERE IS_ACTIVE = 'Y'
),
UPDATED_AT = CURRENT_TIMESTAMP
WHERE STAT_DATE = TRUNC(CURRENT_DATE);

COMMIT;

PROMPT ===== 79310 특약 데이터 수정 완료 =====





