-- 79310 특약 코드 데이터 확인
SELECT CODE, PRODUCT_NAME, PAY_TERM, ENTRY_AGE_M, ENTRY_AGE_F, PERIOD_LABEL
FROM UW_CODE_MAPPING 
WHERE CODE = '79310'
ORDER BY CODE, PERIOD_LABEL, PAY_TERM;

-- 해약환급금 미지급형V2 관련 데이터 확인
SELECT CODE, PRODUCT_NAME, PAY_TERM, ENTRY_AGE_M, ENTRY_AGE_F, PERIOD_LABEL
FROM UW_CODE_MAPPING 
WHERE PRODUCT_NAME LIKE '%해약환급금%' 
   OR PRODUCT_NAME LIKE '%미지급형%'
ORDER BY CODE, PERIOD_LABEL, PAY_TERM;

-- 허혈심장질환진단특약 관련 데이터 확인
SELECT CODE, PRODUCT_NAME, PAY_TERM, ENTRY_AGE_M, ENTRY_AGE_F, PERIOD_LABEL
FROM UW_CODE_MAPPING 
WHERE PRODUCT_NAME LIKE '%허혈심장%'
ORDER BY CODE, PERIOD_LABEL, PAY_TERM;





