-- 1. 21844 상품의 학습된 패턴 조회
SELECT 
    PATTERN_ID,
    INSU_CD,
    FIELD_NAME,
    PATTERN_VALUE,
    CONFIDENCE_SCORE,
    PRIORITY,
    LEARNING_SOURCE,
    IS_ACTIVE,
    CREATED_AT
FROM LEARNED_PATTERN 
WHERE INSU_CD = '21844'
  AND FIELD_NAME = 'ageRange'
  AND IS_ACTIVE = 'Y'
ORDER BY PRIORITY DESC, CONFIDENCE_SCORE DESC;

-- 2. 21844 상품의 UW_CODE_MAPPING 데이터 분석
SELECT 
    CODE,
    PERIOD_LABEL as INSURANCE_TERM,
    PAY_TERM,
    ENTRY_AGE_M as MALE_AGE,
    ENTRY_AGE_F as FEMALE_AGE,
    COUNT(*) as RECORD_COUNT
FROM UW_CODE_MAPPING 
WHERE CODE = '21844'
GROUP BY CODE, PERIOD_LABEL, PAY_TERM, ENTRY_AGE_M, ENTRY_AGE_F
ORDER BY PERIOD_LABEL, PAY_TERM;

-- 3. 21844 상품의 수정 로그 분석
SELECT 
    LOG_ID,
    INSU_CD,
    ORIGINAL_AGE_RANGE,
    CORRECTED_AGE_RANGE,
    CORRECTED_FIELD_COUNT,
    CORRECTION_REASON,
    TIMESTAMP
FROM CORRECTION_LOG 
WHERE INSU_CD = '21844'
ORDER BY TIMESTAMP DESC
FETCH FIRST 10 ROWS ONLY;

-- 4. 가입나이 패턴 분석 (정규화된 형태)
SELECT 
    CODE,
    CASE 
        WHEN ENTRY_AGE_M = ENTRY_AGE_F THEN '남: ' || ENTRY_AGE_M || ', 여: ' || ENTRY_AGE_F
        ELSE '남: ' || ENTRY_AGE_M || ', 여: ' || ENTRY_AGE_F
    END as STANDARD_AGE_PATTERN,
    COUNT(*) as PATTERN_COUNT
FROM UW_CODE_MAPPING 
WHERE CODE = '21844'
  AND ENTRY_AGE_M IS NOT NULL 
  AND ENTRY_AGE_F IS NOT NULL
GROUP BY CODE, ENTRY_AGE_M, ENTRY_AGE_F
ORDER BY PATTERN_COUNT DESC;




