-- 21844 상품의 학습된 패턴 확인
SELECT 
    PATTERN_ID,
    INSU_CD,
    FIELD_NAME,
    PATTERN_VALUE,
    CONFIDENCE_SCORE,
    PRIORITY,
    LEARNING_SOURCE,
    IS_ACTIVE,
    CREATED_AT
FROM LEARNED_PATTERN 
WHERE INSU_CD = '21844'
  AND FIELD_NAME = 'ageRange'
  AND IS_ACTIVE = 'Y'
ORDER BY PRIORITY DESC, CONFIDENCE_SCORE DESC;

-- 전체 학습된 패턴 수 확인
SELECT 
    INSU_CD,
    FIELD_NAME,
    COUNT(*) as PATTERN_COUNT,
    MAX(CONFIDENCE_SCORE) as MAX_CONFIDENCE,
    MAX(PRIORITY) as MAX_PRIORITY
FROM LEARNED_PATTERN 
WHERE IS_ACTIVE = 'Y'
GROUP BY INSU_CD, FIELD_NAME
ORDER BY INSU_CD, FIELD_NAME;

-- 최근 수정 로그 확인
SELECT 
    LOG_ID,
    INSU_CD,
    ORIGINAL_AGE_RANGE,
    CORRECTED_AGE_RANGE,
    CORRECTED_FIELD_COUNT,
    TIMESTAMP
FROM CORRECTION_LOG 
WHERE INSU_CD = '21844'
ORDER BY TIMESTAMP DESC
FETCH FIRST 5 ROWS ONLY;




