-- ========================================
-- 증분 학습 시스템 - 완전 설치 스크립트
-- 모든 오류 해결 (시퀀스 + 테이블 + 이관)
-- ========================================

-- ========================================
-- Step 1: 기존 객체 정리 (있으면 삭제)
-- ========================================

-- 외래키 제약 먼저 삭제 (있으면)
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE LEARNED_PATTERN DROP CONSTRAINT FK_PATTERN_LOG';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE FEW_SHOT_EXAMPLE DROP CONSTRAINT FK_EXAMPLE_LOG';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE FEW_SHOT_EXAMPLE DROP CONSTRAINT FK_EXAMPLE_PATTERN';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- 테이블 삭제
DROP TABLE CORRECTION_LOG CASCADE CONSTRAINTS;
DROP TABLE LEARNED_PATTERN CASCADE CONSTRAINTS;
DROP TABLE FEW_SHOT_EXAMPLE CASCADE CONSTRAINTS;
DROP TABLE LEARNING_STATISTICS CASCADE CONSTRAINTS;

-- 시퀀스 삭제
DROP SEQUENCE correction_log_seq;
DROP SEQUENCE learned_pattern_seq;
DROP SEQUENCE few_shot_example_seq;
DROP SEQUENCE learning_statistics_seq;

SELECT '=== 정리 완료 ===' AS INFO FROM DUAL;


-- ========================================
-- Step 2: 시퀀스 생성
-- ========================================

CREATE SEQUENCE correction_log_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE learned_pattern_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE few_shot_example_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE learning_statistics_seq START WITH 1 INCREMENT BY 1;

SELECT '=== 시퀀스 생성 완료 ===' AS INFO FROM DUAL;


-- ========================================
-- Step 3: 테이블 생성
-- ========================================

-- CORRECTION_LOG 테이블
CREATE TABLE CORRECTION_LOG (
    LOG_ID NUMBER PRIMARY KEY,
    INSU_CD VARCHAR2(20) NOT NULL,
    SRC_FILE VARCHAR2(50),
    PRODUCT_NAME VARCHAR2(200),
    
    ORIGINAL_INSU_TERM VARCHAR2(200),
    ORIGINAL_PAY_TERM VARCHAR2(500),
    ORIGINAL_AGE_RANGE VARCHAR2(1000),
    ORIGINAL_RENEW VARCHAR2(50),
    ORIGINAL_SPECIAL_NOTES VARCHAR2(500),
    ORIGINAL_VALIDATION_SOURCE VARCHAR2(100),
    
    CORRECTED_INSU_TERM VARCHAR2(200),
    CORRECTED_PAY_TERM VARCHAR2(500),
    CORRECTED_AGE_RANGE VARCHAR2(1000),
    CORRECTED_RENEW VARCHAR2(50),
    CORRECTED_SPECIAL_NOTES VARCHAR2(500),
    
    PDF_TEXT CLOB,
    CORRECTED_FIELD_COUNT NUMBER DEFAULT 0,
    CORRECTION_REASON VARCHAR2(500),
    USER_ID VARCHAR2(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    IS_LEARNED CHAR(1) DEFAULT 'N',
    LEARNED_AT TIMESTAMP,
    LEARNING_PATTERN_ID NUMBER,
    
    VALIDATION_SCORE NUMBER,
    IS_VERIFIED CHAR(1) DEFAULT 'N',
    VERIFIED_BY VARCHAR2(50),
    VERIFIED_AT TIMESTAMP,
    
    CREATED_DATE DATE DEFAULT TRUNC(SYSDATE)
);

CREATE INDEX IDX_CORRECTION_INSU_CD ON CORRECTION_LOG(INSU_CD);
CREATE INDEX IDX_CORRECTION_CREATED_AT ON CORRECTION_LOG(CREATED_AT);

SELECT '=== CORRECTION_LOG 생성 완료 ===' AS INFO FROM DUAL;


-- LEARNED_PATTERN 테이블
CREATE TABLE LEARNED_PATTERN (
    PATTERN_ID NUMBER PRIMARY KEY,
    INSU_CD VARCHAR2(20) NOT NULL,
    FIELD_NAME VARCHAR2(50) NOT NULL,
    PATTERN_VALUE VARCHAR2(1000) NOT NULL,
    CONFIDENCE_SCORE NUMBER DEFAULT 100,
    APPLY_COUNT NUMBER DEFAULT 0,
    SUCCESS_COUNT NUMBER DEFAULT 0,
    LEARNED_FROM_LOG_ID NUMBER,
    LEARNING_SOURCE VARCHAR2(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IS_ACTIVE CHAR(1) DEFAULT 'Y',
    PRIORITY NUMBER DEFAULT 50,
    CONSTRAINT UK_PATTERN UNIQUE (INSU_CD, FIELD_NAME)
);

CREATE INDEX IDX_PATTERN_INSU_CD ON LEARNED_PATTERN(INSU_CD);
CREATE INDEX IDX_PATTERN_IS_ACTIVE ON LEARNED_PATTERN(IS_ACTIVE);

SELECT '=== LEARNED_PATTERN 생성 완료 ===' AS INFO FROM DUAL;


-- FEW_SHOT_EXAMPLE 테이블
CREATE TABLE FEW_SHOT_EXAMPLE (
    EXAMPLE_ID NUMBER PRIMARY KEY,
    INSU_CD VARCHAR2(20) NOT NULL,
    PRODUCT_NAME VARCHAR2(200),
    INPUT_TEXT CLOB,
    OUTPUT_INSU_TERM VARCHAR2(200),
    OUTPUT_PAY_TERM VARCHAR2(500),
    OUTPUT_AGE_RANGE VARCHAR2(1000),
    OUTPUT_RENEW VARCHAR2(50),
    EXAMPLE_TYPE VARCHAR2(50),
    QUALITY_SCORE NUMBER DEFAULT 100,
    USE_COUNT NUMBER DEFAULT 0,
    SUCCESS_RATE NUMBER,
    IS_ACTIVE CHAR(1) DEFAULT 'Y',
    PRIORITY NUMBER DEFAULT 50,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SOURCE_LOG_ID NUMBER,
    RELATED_PATTERN_ID NUMBER
);

CREATE INDEX IDX_FEW_SHOT_INSU_CD ON FEW_SHOT_EXAMPLE(INSU_CD);

SELECT '=== FEW_SHOT_EXAMPLE 생성 완료 ===' AS INFO FROM DUAL;


-- LEARNING_STATISTICS 테이블
CREATE TABLE LEARNING_STATISTICS (
    STAT_ID NUMBER PRIMARY KEY,
    STAT_DATE DATE DEFAULT TRUNC(SYSDATE),
    TOTAL_CORRECTIONS NUMBER DEFAULT 0,
    TOTAL_PATTERNS NUMBER DEFAULT 0,
    TOTAL_FEW_SHOT_EXAMPLES NUMBER DEFAULT 0,
    INITIAL_ACCURACY NUMBER,
    CURRENT_ACCURACY NUMBER,
    ACCURACY_IMPROVEMENT NUMBER,
    DAILY_PARSING_COUNT NUMBER DEFAULT 0,
    DAILY_CORRECTION_COUNT NUMBER DEFAULT 0,
    DAILY_SUCCESS_RATE NUMBER,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX UK_LEARNING_STAT_DATE ON LEARNING_STATISTICS(STAT_DATE);

SELECT '=== LEARNING_STATISTICS 생성 완료 ===' AS INFO FROM DUAL;


-- ========================================
-- Step 4: UW_CODE_MAPPING 확인
-- ========================================

SELECT '=== UW_CODE_MAPPING 확인 ===' AS INFO FROM DUAL;

SELECT COUNT(*) AS UW_CODE_MAPPING_COUNT FROM UW_CODE_MAPPING;


-- ========================================
-- Step 5: LEARNED_PATTERN으로 이관
-- ========================================

-- 보험기간(insuTerm)
INSERT INTO LEARNED_PATTERN (
    PATTERN_ID, INSU_CD, FIELD_NAME, PATTERN_VALUE, 
    CONFIDENCE_SCORE, LEARNING_SOURCE, PRIORITY, IS_ACTIVE
)
SELECT 
    learned_pattern_seq.NEXTVAL,
    CODE,
    'insuTerm',
    PERIOD_LABEL,
    100,
    'UW_MAPPING',
    100,
    'Y'
FROM (
    SELECT DISTINCT CODE, PERIOD_LABEL
    FROM UW_CODE_MAPPING
    WHERE PERIOD_LABEL IS NOT NULL
    ORDER BY CODE
);

SELECT 'insuTerm 이관: ' || SQL%ROWCOUNT || '건' AS INFO FROM DUAL;


-- 납입기간(payTerm)
INSERT INTO LEARNED_PATTERN (
    PATTERN_ID, INSU_CD, FIELD_NAME, PATTERN_VALUE, 
    CONFIDENCE_SCORE, LEARNING_SOURCE, PRIORITY, IS_ACTIVE
)
SELECT 
    learned_pattern_seq.NEXTVAL,
    CODE,
    'payTerm',
    PAY_TERM,
    100,
    'UW_MAPPING',
    100,
    'Y'
FROM (
    SELECT DISTINCT CODE, PAY_TERM
    FROM UW_CODE_MAPPING
    WHERE PAY_TERM IS NOT NULL
    ORDER BY CODE
);

SELECT 'payTerm 이관: ' || SQL%ROWCOUNT || '건' AS INFO FROM DUAL;


-- 가입나이(ageRange)
INSERT INTO LEARNED_PATTERN (
    PATTERN_ID, INSU_CD, FIELD_NAME, PATTERN_VALUE, 
    CONFIDENCE_SCORE, LEARNING_SOURCE, PRIORITY, IS_ACTIVE
)
SELECT 
    learned_pattern_seq.NEXTVAL,
    CODE,
    'ageRange',
    ENTRY_AGE_M,
    100,
    'UW_MAPPING',
    100,
    'Y'
FROM (
    SELECT DISTINCT CODE, ENTRY_AGE_M
    FROM UW_CODE_MAPPING
    WHERE ENTRY_AGE_M IS NOT NULL
    ORDER BY CODE
);

SELECT 'ageRange 이관: ' || SQL%ROWCOUNT || '건' AS INFO FROM DUAL;


-- ========================================
-- Step 6: 샘플 데이터
-- ========================================

-- 샘플 통계
INSERT INTO LEARNING_STATISTICS (
    STAT_ID, STAT_DATE, 
    TOTAL_CORRECTIONS, TOTAL_PATTERNS, TOTAL_FEW_SHOT_EXAMPLES,
    INITIAL_ACCURACY, CURRENT_ACCURACY, ACCURACY_IMPROVEMENT
) VALUES (
    learning_statistics_seq.NEXTVAL, TRUNC(SYSDATE),
    0, 15, 0,
    75.0, 75.0, 0.0
);

COMMIT;

SELECT '=== 설치 완료! ===' AS INFO FROM DUAL;


-- ========================================
-- Step 7: 결과 확인
-- ========================================

SELECT '=== 최종 결과 ===' AS INFO FROM DUAL;

-- 전체 테이블 건수
SELECT 'CORRECTION_LOG: ' || COUNT(*) || '건' AS INFO FROM CORRECTION_LOG
UNION ALL
SELECT 'LEARNED_PATTERN: ' || COUNT(*) || '건' AS INFO FROM LEARNED_PATTERN
UNION ALL
SELECT 'FEW_SHOT_EXAMPLE: ' || COUNT(*) || '건' AS INFO FROM FEW_SHOT_EXAMPLE
UNION ALL
SELECT 'LEARNING_STATISTICS: ' || COUNT(*) || '건' AS INFO FROM LEARNING_STATISTICS;

-- 필드별 분포
SELECT '=== 필드별 분포 ===' AS INFO FROM DUAL;

SELECT 
    FIELD_NAME,
    COUNT(*) AS CNT
FROM LEARNED_PATTERN
GROUP BY FIELD_NAME
ORDER BY FIELD_NAME;

-- 학습 소스
SELECT '=== 학습 소스 ===' AS INFO FROM DUAL;

SELECT 
    LEARNING_SOURCE,
    COUNT(*) AS CNT
FROM LEARNED_PATTERN
GROUP BY LEARNING_SOURCE;

-- 중복 확인 (없어야 정상!)
SELECT '=== 중복 확인 (없어야 정상) ===' AS INFO FROM DUAL;

SELECT 
    INSU_CD,
    FIELD_NAME,
    COUNT(*) AS CNT
FROM LEARNED_PATTERN
GROUP BY INSU_CD, FIELD_NAME
HAVING COUNT(*) > 1;

-- 중복이 없으면 "no rows selected" 출력 (정상!)

SELECT '완료!' AS STATUS FROM DUAL;






