-- ========================================
-- 증분 학습 시스템 테이블 스키마
-- 작성일: 2025-10-13
-- 목적: UW_CODE_MAPPING 기반 증분 학습 시스템 구축
-- ========================================

-- ========================================
-- 1. CORRECTION_LOG 테이블
-- 목적: 사용자의 모든 수정사항 기록 (증분 학습의 핵심)
-- ========================================

-- 기존 테이블 삭제 (개발 환경)
DROP TABLE CORRECTION_LOG CASCADE CONSTRAINTS;
DROP SEQUENCE correction_log_seq;

-- 시퀀스 생성
CREATE SEQUENCE correction_log_seq START WITH 1 INCREMENT BY 1;

-- CORRECTION_LOG 테이블 생성
CREATE TABLE CORRECTION_LOG (
    -- 기본 정보
    LOG_ID NUMBER PRIMARY KEY,
    INSU_CD VARCHAR2(20) NOT NULL,
    SRC_FILE VARCHAR2(50),
    PRODUCT_NAME VARCHAR2(200),
    
    -- 원본 파싱 결과 (JSON 형태)
    ORIGINAL_INSU_TERM VARCHAR2(200),
    ORIGINAL_PAY_TERM VARCHAR2(500),
    ORIGINAL_AGE_RANGE VARCHAR2(1000),
    ORIGINAL_RENEW VARCHAR2(50),
    ORIGINAL_SPECIAL_NOTES VARCHAR2(500),
    ORIGINAL_VALIDATION_SOURCE VARCHAR2(100),
    
    -- 사용자 수정 결과
    CORRECTED_INSU_TERM VARCHAR2(200),
    CORRECTED_PAY_TERM VARCHAR2(500),
    CORRECTED_AGE_RANGE VARCHAR2(1000),
    CORRECTED_RENEW VARCHAR2(50),
    CORRECTED_SPECIAL_NOTES VARCHAR2(500),
    
    -- 수정 메타데이터
    PDF_TEXT CLOB,                           -- 학습용 PDF 원문
    CORRECTED_FIELD_COUNT NUMBER DEFAULT 0,  -- 수정된 필드 개수
    CORRECTION_REASON VARCHAR2(500),         -- 수정 이유
    USER_ID VARCHAR2(50),                    -- 수정자
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- 학습 상태
    IS_LEARNED CHAR(1) DEFAULT 'N',          -- 학습 완료 여부 (Y/N)
    LEARNED_AT TIMESTAMP,                    -- 학습 처리 시간
    LEARNING_PATTERN_ID NUMBER,              -- 연결된 학습 패턴 ID
    
    -- 검증 정보
    VALIDATION_SCORE NUMBER,                 -- 검증 점수 (0-100)
    IS_VERIFIED CHAR(1) DEFAULT 'N',         -- 관리자 검증 여부
    VERIFIED_BY VARCHAR2(50),
    VERIFIED_AT TIMESTAMP,
    
    -- 인덱스용 컬럼
    CREATED_DATE DATE DEFAULT TRUNC(SYSDATE)
);

-- 인덱스 생성 (성능 최적화)
CREATE INDEX IDX_CORRECTION_INSU_CD ON CORRECTION_LOG(INSU_CD);
CREATE INDEX IDX_CORRECTION_CREATED_AT ON CORRECTION_LOG(CREATED_AT);
CREATE INDEX IDX_CORRECTION_IS_LEARNED ON CORRECTION_LOG(IS_LEARNED);
CREATE INDEX IDX_CORRECTION_CREATED_DATE ON CORRECTION_LOG(CREATED_DATE);
CREATE INDEX IDX_CORRECTION_USER_ID ON CORRECTION_LOG(USER_ID);

-- 코멘트 추가
COMMENT ON TABLE CORRECTION_LOG IS '사용자 파싱 결과 수정 로그 (증분 학습 데이터)';
COMMENT ON COLUMN CORRECTION_LOG.LOG_ID IS '로그 고유 ID';
COMMENT ON COLUMN CORRECTION_LOG.INSU_CD IS '보험 상품 코드';
COMMENT ON COLUMN CORRECTION_LOG.IS_LEARNED IS '학습 패턴 생성 완료 여부';
COMMENT ON COLUMN CORRECTION_LOG.IS_VERIFIED IS '관리자 검증 완료 여부 (품질 관리)';


-- ========================================
-- 2. LEARNED_PATTERN 테이블
-- 목적: 학습된 패턴 저장 (빠른 적용을 위한 캐시)
-- ========================================

DROP TABLE LEARNED_PATTERN CASCADE CONSTRAINTS;
DROP SEQUENCE learned_pattern_seq;

CREATE SEQUENCE learned_pattern_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE LEARNED_PATTERN (
    -- 기본 정보
    PATTERN_ID NUMBER PRIMARY KEY,
    INSU_CD VARCHAR2(20) NOT NULL,
    FIELD_NAME VARCHAR2(50) NOT NULL,        -- insuTerm, payTerm, ageRange, renew
    
    -- 패턴 정보
    PATTERN_VALUE VARCHAR2(1000) NOT NULL,   -- 학습된 올바른 값
    CONFIDENCE_SCORE NUMBER DEFAULT 100,      -- 신뢰도 (0-100)
    APPLY_COUNT NUMBER DEFAULT 0,             -- 적용 횟수
    SUCCESS_COUNT NUMBER DEFAULT 0,           -- 성공 횟수
    
    -- 학습 메타데이터
    LEARNED_FROM_LOG_ID NUMBER,              -- 원본 CORRECTION_LOG ID
    LEARNING_SOURCE VARCHAR2(50),            -- UW_MAPPING, USER_CORRECTION, AUTO_LEARNED
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- 패턴 상태
    IS_ACTIVE CHAR(1) DEFAULT 'Y',           -- 활성화 여부
    PRIORITY NUMBER DEFAULT 50,               -- 우선순위 (높을수록 우선)
    
    -- 복합 키 제약
    CONSTRAINT UK_PATTERN UNIQUE (INSU_CD, FIELD_NAME)
);

-- 인덱스 생성
CREATE INDEX IDX_PATTERN_INSU_CD ON LEARNED_PATTERN(INSU_CD);
CREATE INDEX IDX_PATTERN_IS_ACTIVE ON LEARNED_PATTERN(IS_ACTIVE);
CREATE INDEX IDX_PATTERN_PRIORITY ON LEARNED_PATTERN(PRIORITY DESC);

COMMENT ON TABLE LEARNED_PATTERN IS '학습된 파싱 패턴 (증분 학습 결과)';
COMMENT ON COLUMN LEARNED_PATTERN.CONFIDENCE_SCORE IS '패턴 신뢰도 (사용자 수정 횟수 기반)';
COMMENT ON COLUMN LEARNED_PATTERN.LEARNING_SOURCE IS 'UW_MAPPING: 초기 데이터, USER_CORRECTION: 사용자 수정, AUTO_LEARNED: 자동 학습';


-- ========================================
-- 3. LEARNING_STATISTICS 테이블
-- 목적: 학습 효과 추적 및 대시보드용 통계
-- ========================================

DROP TABLE LEARNING_STATISTICS CASCADE CONSTRAINTS;

CREATE TABLE LEARNING_STATISTICS (
    -- 기본 정보
    STAT_ID NUMBER PRIMARY KEY,
    STAT_DATE DATE DEFAULT TRUNC(SYSDATE),
    
    -- 전체 통계
    TOTAL_CORRECTIONS NUMBER DEFAULT 0,      -- 총 수정 건수
    TOTAL_PATTERNS NUMBER DEFAULT 0,          -- 학습된 패턴 수
    TOTAL_FEW_SHOT_EXAMPLES NUMBER DEFAULT 0, -- Few-Shot 예시 수
    
    -- 정확도 통계
    INITIAL_ACCURACY NUMBER,                  -- 초기 정확도
    CURRENT_ACCURACY NUMBER,                  -- 현재 정확도
    ACCURACY_IMPROVEMENT NUMBER,              -- 정확도 향상치
    
    -- 일별 통계
    DAILY_PARSING_COUNT NUMBER DEFAULT 0,     -- 일일 파싱 건수
    DAILY_CORRECTION_COUNT NUMBER DEFAULT 0,  -- 일일 수정 건수
    DAILY_SUCCESS_RATE NUMBER,                -- 일일 성공률
    
    -- 필드별 정확도
    INSU_TERM_ACCURACY NUMBER,
    PAY_TERM_ACCURACY NUMBER,
    AGE_RANGE_ACCURACY NUMBER,
    RENEW_ACCURACY NUMBER,
    
    -- 상품별 통계
    TOP_5_ERROR_PRODUCTS VARCHAR2(500),       -- 자주 틀리는 상품 Top 5
    TOP_5_SUCCESS_PRODUCTS VARCHAR2(500),     -- 정확도 높은 상품 Top 5
    
    -- 타임스탬프
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 시퀀스 생성
CREATE SEQUENCE learning_statistics_seq START WITH 1 INCREMENT BY 1;

-- 인덱스 생성
CREATE UNIQUE INDEX UK_LEARNING_STAT_DATE ON LEARNING_STATISTICS(STAT_DATE);
CREATE INDEX IDX_LEARNING_STAT_CREATED ON LEARNING_STATISTICS(CREATED_AT);

COMMENT ON TABLE LEARNING_STATISTICS IS '증분 학습 통계 (일별 집계)';


-- ========================================
-- 4. FEW_SHOT_EXAMPLE 테이블
-- 목적: Few-Shot Learning 예시 관리
-- ========================================

DROP TABLE FEW_SHOT_EXAMPLE CASCADE CONSTRAINTS;
DROP SEQUENCE few_shot_example_seq;

CREATE SEQUENCE few_shot_example_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE FEW_SHOT_EXAMPLE (
    -- 기본 정보
    EXAMPLE_ID NUMBER PRIMARY KEY,
    INSU_CD VARCHAR2(20) NOT NULL,
    PRODUCT_NAME VARCHAR2(200),
    
    -- 예시 데이터
    INPUT_TEXT CLOB,                          -- 입력 예시 (PDF 텍스트)
    OUTPUT_INSU_TERM VARCHAR2(200),
    OUTPUT_PAY_TERM VARCHAR2(500),
    OUTPUT_AGE_RANGE VARCHAR2(1000),
    OUTPUT_RENEW VARCHAR2(50),
    
    -- 예시 메타데이터
    EXAMPLE_TYPE VARCHAR2(50),                -- INITIAL, USER_CORRECTED, AUTO_GENERATED
    QUALITY_SCORE NUMBER DEFAULT 100,         -- 예시 품질 점수
    USE_COUNT NUMBER DEFAULT 0,               -- 사용 횟수
    SUCCESS_RATE NUMBER,                      -- 성공률 (사용 시 성공한 비율)
    
    -- 상태 관리
    IS_ACTIVE CHAR(1) DEFAULT 'Y',
    PRIORITY NUMBER DEFAULT 50,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- 연결 정보
    SOURCE_LOG_ID NUMBER,                     -- 원본 CORRECTION_LOG ID
    RELATED_PATTERN_ID NUMBER                 -- 관련 LEARNED_PATTERN ID
);

-- 인덱스 생성
CREATE INDEX IDX_FEW_SHOT_INSU_CD ON FEW_SHOT_EXAMPLE(INSU_CD);
CREATE INDEX IDX_FEW_SHOT_IS_ACTIVE ON FEW_SHOT_EXAMPLE(IS_ACTIVE);
CREATE INDEX IDX_FEW_SHOT_PRIORITY ON FEW_SHOT_EXAMPLE(PRIORITY DESC);
CREATE INDEX IDX_FEW_SHOT_QUALITY ON FEW_SHOT_EXAMPLE(QUALITY_SCORE DESC);

COMMENT ON TABLE FEW_SHOT_EXAMPLE IS 'Few-Shot Learning 예시 저장소';
COMMENT ON COLUMN FEW_SHOT_EXAMPLE.QUALITY_SCORE IS '예시 품질 (사용 빈도 및 성공률 기반)';


-- ========================================
-- 5. 외래키 제약 추가 (선택적)
-- ========================================

-- LEARNED_PATTERN → CORRECTION_LOG
ALTER TABLE LEARNED_PATTERN ADD CONSTRAINT FK_PATTERN_LOG
    FOREIGN KEY (LEARNED_FROM_LOG_ID) REFERENCES CORRECTION_LOG(LOG_ID) ON DELETE SET NULL;

-- FEW_SHOT_EXAMPLE → CORRECTION_LOG
ALTER TABLE FEW_SHOT_EXAMPLE ADD CONSTRAINT FK_EXAMPLE_LOG
    FOREIGN KEY (SOURCE_LOG_ID) REFERENCES CORRECTION_LOG(LOG_ID) ON DELETE SET NULL;

-- FEW_SHOT_EXAMPLE → LEARNED_PATTERN
ALTER TABLE FEW_SHOT_EXAMPLE ADD CONSTRAINT FK_EXAMPLE_PATTERN
    FOREIGN KEY (RELATED_PATTERN_ID) REFERENCES LEARNED_PATTERN(PATTERN_ID) ON DELETE SET NULL;


-- ========================================
-- 6. 초기 데이터: UW_CODE_MAPPING → LEARNED_PATTERN 이관
-- 목적: 기존 정확한 데이터를 학습 패턴으로 등록
-- ========================================

-- UW_CODE_MAPPING 데이터를 LEARNED_PATTERN으로 변환
-- 수정: GROUP BY와 SEQUENCE 충돌 해결 (서브쿼리 사용)

-- 보험기간(insuTerm) 패턴
INSERT INTO LEARNED_PATTERN (
    PATTERN_ID, INSU_CD, FIELD_NAME, PATTERN_VALUE, 
    CONFIDENCE_SCORE, LEARNING_SOURCE, PRIORITY, IS_ACTIVE
)
SELECT 
    learned_pattern_seq.NEXTVAL,
    CODE,
    'insuTerm',
    PERIOD_LABEL,
    100,
    'UW_MAPPING',
    100,
    'Y'
FROM (
    SELECT DISTINCT CODE, PERIOD_LABEL
    FROM UW_CODE_MAPPING
    WHERE PERIOD_LABEL IS NOT NULL
    ORDER BY CODE, PERIOD_LABEL
);

-- 납입기간(payTerm) 패턴
INSERT INTO LEARNED_PATTERN (
    PATTERN_ID, INSU_CD, FIELD_NAME, PATTERN_VALUE, 
    CONFIDENCE_SCORE, LEARNING_SOURCE, PRIORITY, IS_ACTIVE
)
SELECT 
    learned_pattern_seq.NEXTVAL,
    CODE,
    'payTerm',
    PAY_TERM,
    100,
    'UW_MAPPING',
    100,
    'Y'
FROM (
    SELECT DISTINCT CODE, PAY_TERM
    FROM UW_CODE_MAPPING
    WHERE PAY_TERM IS NOT NULL
    ORDER BY CODE, PAY_TERM
);

-- 가입나이(ageRange) 패턴
INSERT INTO LEARNED_PATTERN (
    PATTERN_ID, INSU_CD, FIELD_NAME, PATTERN_VALUE, 
    CONFIDENCE_SCORE, LEARNING_SOURCE, PRIORITY, IS_ACTIVE
)
SELECT 
    learned_pattern_seq.NEXTVAL,
    CODE,
    'ageRange',
    ENTRY_AGE_M,
    100,
    'UW_MAPPING',
    100,
    'Y'
FROM (
    SELECT DISTINCT CODE, ENTRY_AGE_M
    FROM UW_CODE_MAPPING
    WHERE ENTRY_AGE_M IS NOT NULL
    ORDER BY CODE, ENTRY_AGE_M
);

COMMIT;


-- ========================================
-- 7. 샘플 데이터 (테스트용)
-- ========================================

-- 샘플 수정 로그
INSERT INTO CORRECTION_LOG (
    LOG_ID, INSU_CD, PRODUCT_NAME,
    ORIGINAL_INSU_TERM, ORIGINAL_PAY_TERM, ORIGINAL_AGE_RANGE, ORIGINAL_RENEW,
    CORRECTED_INSU_TERM, CORRECTED_PAY_TERM, CORRECTED_AGE_RANGE, CORRECTED_RENEW,
    CORRECTED_FIELD_COUNT, USER_ID, IS_LEARNED
) VALUES (
    correction_log_seq.NEXTVAL, '21686', '(무)흥국생명 다사랑암보험',
    '종신', '10년납', '15~80', '비갱신형',
    '종신', '10년납, 15년납, 20년납, 30년납', '10년납(남:15~80,여:15~80)', '비갱신형',
    2, 'admin', 'N'
);

-- 샘플 통계 (오늘)
INSERT INTO LEARNING_STATISTICS (
    STAT_ID, STAT_DATE, 
    TOTAL_CORRECTIONS, TOTAL_PATTERNS, TOTAL_FEW_SHOT_EXAMPLES,
    INITIAL_ACCURACY, CURRENT_ACCURACY, ACCURACY_IMPROVEMENT,
    DAILY_PARSING_COUNT, DAILY_CORRECTION_COUNT, DAILY_SUCCESS_RATE
) VALUES (
    learning_statistics_seq.NEXTVAL, TRUNC(SYSDATE),
    0, 15, 5,
    75.0, 75.0, 0.0,
    0, 0, 0.0
);

COMMIT;


-- ========================================
-- 8. 데이터 확인
-- ========================================

SELECT '=== CORRECTION_LOG ===' AS INFO FROM DUAL;
SELECT COUNT(*) AS TOTAL_CORRECTIONS FROM CORRECTION_LOG;

SELECT '=== LEARNED_PATTERN ===' AS INFO FROM DUAL;
SELECT COUNT(*) AS TOTAL_PATTERNS FROM LEARNED_PATTERN;
SELECT LEARNING_SOURCE, COUNT(*) AS CNT FROM LEARNED_PATTERN GROUP BY LEARNING_SOURCE;

SELECT '=== FEW_SHOT_EXAMPLE ===' AS INFO FROM DUAL;
SELECT COUNT(*) AS TOTAL_EXAMPLES FROM FEW_SHOT_EXAMPLE;

SELECT '=== LEARNING_STATISTICS ===' AS INFO FROM DUAL;
SELECT * FROM LEARNING_STATISTICS WHERE STAT_DATE = TRUNC(SYSDATE);

SELECT '테이블 생성 완료!' AS STATUS FROM DUAL;

